### ISSUE TITLE
关于一万词汇表的问题

### ISSUE THREAD

**Issue by LePtC** [Celthi/meltSubtitles#1]
你这个一万词汇表用的是 google-10000-english 吧？这个表里面有很多 mb mr le 这样无意义的词，不知道你是否有办法清洗一下这个数据库？

**Comment by Celthi** [comment]
如果对这样的词不感兴趣，那么它们留在库里对效果没有影响，因为它们不会显示在字幕中，不好的地方是会让程序可能多占内存。如果要去掉需要有标准，[源库](https://github.com/first20hours/google-10000-english)，所以更好的办法是找到另外更合适的库。
